# basic makefile

var := "Test variable"

include abc.mk

print_hello:
	@echo "Hello Makefile"
print_hello2: print_hello
	@echo "Hello 2024 \
Welcome to make road"

test_var:
	@echo "test_var $(var)"
	
	