#makefile project demo

PRO_DIR := .

INC_DIR := $(PRO_DIR)/inc
SRC_DIR := $(PRO_DIR)/src

COMPILER_DIR		:= C:\tools\gcc_10_2023\13_2_Rel1
PREFIX_GCC_COMPILER :=
CC				:= 

$(SRC_DIR)/main.c: $(SRC_DIR)/main.c
	@echo "compile $(SRC_DIR)/main.c file"
	
$(SRC_DIR)/startup_ARMCM0.S: $(SRC_DIR)/startup_ARMCM0.S
	@echo "compile $(SRC_DIR)/startup_ARMCM0.S file"

